# Generated by Django 4.1.4 on 2023-02-14 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0003_alter_periodo_options_and_more'),
        ('itinerancia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerancia',
            name='fk_periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerancia_periodo', to='periodo.periodo'),
            preserve_default=False,
        ),
    ]
