# Generated by Django 4.1.4 on 2023-02-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerancia', '0002_itinerancia_fk_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerancia',
            name='nucleos_poblacion',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerancia',
            name='poblado_sede',
            field=models.CharField(max_length=200, verbose_name='Poblado Sede'),
        ),
    ]
