# Generated by Django 4.1.4 on 2023-02-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerancia', '0003_itinerancia_nucleos_poblacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio_atendido',
            name='nucleos_poblacion',
        ),
    ]
