# Generated by Django 4.1.4 on 2022-12-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('fk_tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribunal.tribunal')),
            ],
            options={
                'verbose_name': 'periodo',
                'verbose_name_plural': 'periodos',
                'db_table': 'Periodo',
                'ordering': ['-fecha_inicio_periodo'],
            },
        ),
    ]
