# Generated by Django 4.1.4 on 2022-12-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
