# Generated by Django 4.1.4 on 2022-12-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribunal',
            name='estado',
            field=models.CharField(choices=[('', ''), ('aguascalientes', 'Aguascalientes'), ('baja_california', 'Baja California'), ('baja_california_sur', 'Baja California Sur'), ('campeche', 'Campeche'), ('chiapas', 'Chiapas'), ('chihuahua', 'Chihuahua'), ('coahuila', 'Coahuila'), ('colima', 'Colima'), ('cdmx', 'Ciudad de México / CDMX'), ('durango', 'Durango'), ('estado_de_mexico', 'Estado de México'), ('guanajuato', 'Guanajuato'), ('guerrero', 'Guerrero'), ('hidalgo', 'Hidalgo'), ('jalisco', 'Jalisco'), ('michoacan', 'Michoacán'), ('morelos', 'Morelos'), ('nayarit', 'Nayarit'), ('nuevo_leon', 'Nuevo León'), ('oaxaca', 'Oaxaca'), ('puebla', 'Puebla'), ('querétaro', 'Querétaro'), ('quintana_roo', 'Quintana Roo'), ('san_luis_potosi', 'San Luis Potosí'), ('sinaloa', 'Sinaloa'), ('sonora', 'Sonora'), ('tabasco', 'Tabasco'), ('tamaulipas', 'Tamaulipas'), ('tlaxcala', 'Tlaxcala'), ('veracruz', 'Veracruz'), ('yucatan', 'Yucatán'), ('zacatecas', 'Zacatecas'), ('texcoco', 'Texcoco')], max_length=50),
        ),
    ]
