# Generated by Django 4.1.4 on 2023-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribunal', '0002_alter_tribunal_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunal',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='tribunal',
            name='municipio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
