# Generated by Django 4.1.4 on 2022-12-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_inicio_insp', models.DateField()),
                ('fecha_corte', models.DateField()),
                ('resultado', models.CharField(max_length=200)),
                ('fk_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='periodo.periodo')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
                'db_table': 'VisitaInspeccion',
            },
        ),
    ]
