# Generated by Django 4.1.4 on 2023-01-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita_inspeccion', '0002_rename_fecha_visitainspeccion_fecha_corte_periodo_insp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitainspeccion',
            name='resultado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
