# Generated by Django 4.1.4 on 2023-01-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita_inspeccion', '0003_alter_visitainspeccion_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitainspeccion',
            name='duracion',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
