# Generated by Django 4.1.4 on 2023-01-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0003_alter_periodo_options_and_more'),
        ('visita_inspeccion', '0004_alter_visitainspeccion_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitainspeccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='visitainspeccion',
            name='fk_periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita_periodo', to='periodo.periodo'),
        ),
    ]
