# Generated by Django 4.1.4 on 2022-12-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumen',
            old_name='asuntos_ingresados',
            new_name='asuntos_en_tramite',
        ),
        migrations.AddField(
            model_name='resumen',
            name='asuntos_turnados_a_sentencia',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumen',
            name='ingresos',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
