# Generated by Django 4.1.4 on 2023-01-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodo', '0003_alter_periodo_options_and_more'),
        ('resumen', '0003_resumen_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumen_Año',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentencias', models.DecimalField(decimal_places=0, max_digits=4)),
                ('convenios', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ingresos', models.DecimalField(decimal_places=0, max_digits=4)),
                ('asuntos_en_tramite', models.DecimalField(decimal_places=0, max_digits=4)),
                ('asuntos_turnados_a_sentencia', models.DecimalField(decimal_places=0, max_digits=4)),
                ('archivados', models.DecimalField(decimal_places=0, max_digits=4)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('anio', models.DecimalField(decimal_places=0, max_digits=4)),
                ('itinerancias', models.DecimalField(decimal_places=0, max_digits=2)),
                ('fk_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_anio_periodo', to='periodo.periodo')),
            ],
            options={
                'verbose_name': 'resumen_a',
                'verbose_name_plural': 'resumenes_por_año',
                'db_table': 'Resumen_Por_Año',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Resumen_Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentencias', models.DecimalField(decimal_places=0, max_digits=4)),
                ('convenios', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ingresos', models.DecimalField(decimal_places=0, max_digits=4)),
                ('asuntos_en_tramite', models.DecimalField(decimal_places=0, max_digits=4)),
                ('asuntos_turnados_a_sentencia', models.DecimalField(decimal_places=0, max_digits=4)),
                ('archivados', models.DecimalField(decimal_places=0, max_digits=4)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('itinerancias', models.DecimalField(decimal_places=0, max_digits=2)),
                ('fk_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_entrega_periodo', to='periodo.periodo')),
            ],
            options={
                'verbose_name': 'resumen_entrega',
                'db_table': 'Resumen_Entrega',
            },
        ),
        migrations.CreateModel(
            name='Resumen_Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentencias', models.DecimalField(decimal_places=0, max_digits=4)),
                ('convenios', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ingresos', models.DecimalField(decimal_places=0, max_digits=4)),
                ('asuntos_en_tramite', models.DecimalField(decimal_places=0, max_digits=4)),
                ('asuntos_turnados_a_sentencia', models.DecimalField(decimal_places=0, max_digits=4)),
                ('archivados', models.DecimalField(decimal_places=0, max_digits=4)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fk_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_recepcion_periodo', to='periodo.periodo')),
            ],
            options={
                'verbose_name': 'resumen_recepcion',
                'db_table': 'Resumen_Recepcion',
            },
        ),
        migrations.DeleteModel(
            name='Resumen',
        ),
    ]
