# Generated by Django 4.1.4 on 2023-02-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0005_remove_resumen_año_asuntos_en_tramite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen_año',
            name='diferencia',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
