# Generated by Django 4.1.4 on 2023-02-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0006_resumen_año_diferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen_año',
            name='diferencia',
        ),
    ]
