# Generated by Django 4.1.4 on 2023-02-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0008_asuntos_en_tramite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen_año',
            name='itinerancias',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
