# Generated by Django 4.1.4 on 2023-02-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0009_alter_resumen_año_itinerancias'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen_año',
            name='asuntos_turnados_sentencia',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumen_entrega',
            name='asuntos_turnados_sentencia',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumen_recepcion',
            name='asuntos_turnados_sentencia',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumen_año',
            name='itinerancias',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=2, null=True),
        ),
    ]
