# Generated by Django 4.1.4 on 2023-02-03 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0010_resumen_año_asuntos_turnados_sentencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asuntos_Turnados_A_Sentencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], max_length=15)),
                ('cantidad', models.DecimalField(decimal_places=0, max_digits=4)),
                ('fk_resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asuntosTurnados_resumen', to='resumen.resumen_año')),
            ],
        ),
    ]
