# Generated by Django 4.1.4 on 2023-02-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumen', '0011_asuntos_turnados_a_sentencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen_año',
            name='itinerancias',
        ),
        migrations.RemoveField(
            model_name='resumen_entrega',
            name='itinerancias',
        ),
    ]
